server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    # Extract Docker container information
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attr.tag
      - regex:
          expression: (?P<container_id>[a-z0-9]{64})
          source: filename
      - regex:
          expression: ^(?P<container_name>.*?)(-(?P<container_id>[a-z0-9]{64}))?$
          source: container_id
      - labels:
          container_id:
          container_name:
          stream: